// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseIDResp) Reset() {
	*x = BaseIDResp{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseIDResp) ProtoMessage() {}

func (x *BaseIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseIDResp.ProtoReflect.Descriptor instead.
func (*BaseIDResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *BaseIDResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseIDResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BaseUUIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseUUIDResp) Reset() {
	*x = BaseUUIDResp{}
	mi := &file_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseUUIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseUUIDResp) ProtoMessage() {}

func (x *BaseUUIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseUUIDResp.ProtoReflect.Descriptor instead.
func (*BaseUUIDResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{2}
}

func (x *BaseUUIDResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseUUIDResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// base message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{3}
}

type IDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDReq) Reset() {
	*x = IDReq{}
	mi := &file_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDReq) ProtoMessage() {}

func (x *IDReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDReq.ProtoReflect.Descriptor instead.
func (*IDReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{4}
}

func (x *IDReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IDsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDsReq) Reset() {
	*x = IDsReq{}
	mi := &file_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsReq) ProtoMessage() {}

func (x *IDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsReq.ProtoReflect.Descriptor instead.
func (*IDsReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{5}
}

func (x *IDsReq) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PageInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfoReq) Reset() {
	*x = PageInfoReq{}
	mi := &file_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfoReq) ProtoMessage() {}

func (x *PageInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfoReq.ProtoReflect.Descriptor instead.
func (*PageInfoReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{6}
}

func (x *PageInfoReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfoReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TaskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id"`
	CreatedAt      *int64                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at"`
	UpdatedAt      *int64                 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at"`
	Status         *uint32                `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status"`
	Name           *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name"`
	TaskGroup      *string                `protobuf:"bytes,6,opt,name=task_group,json=taskGroup,proto3,oneof" json:"task_group"`
	CronExpression *string                `protobuf:"bytes,7,opt,name=cron_expression,json=cronExpression,proto3,oneof" json:"cron_expression"`
	Pattern        *string                `protobuf:"bytes,8,opt,name=pattern,proto3,oneof" json:"pattern"`
	Payload        *string                `protobuf:"bytes,9,opt,name=payload,proto3,oneof" json:"payload"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{7}
}

func (x *TaskInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TaskInfo) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *TaskInfo) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *TaskInfo) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TaskInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TaskInfo) GetTaskGroup() string {
	if x != nil && x.TaskGroup != nil {
		return *x.TaskGroup
	}
	return ""
}

func (x *TaskInfo) GetCronExpression() string {
	if x != nil && x.CronExpression != nil {
		return *x.CronExpression
	}
	return ""
}

func (x *TaskInfo) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *TaskInfo) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

type TaskListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name"`
	TaskGroup     *string                `protobuf:"bytes,4,opt,name=task_group,json=taskGroup,proto3,oneof" json:"task_group"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListReq) Reset() {
	*x = TaskListReq{}
	mi := &file_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListReq) ProtoMessage() {}

func (x *TaskListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListReq.ProtoReflect.Descriptor instead.
func (*TaskListReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{8}
}

func (x *TaskListReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TaskListReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *TaskListReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TaskListReq) GetTaskGroup() string {
	if x != nil && x.TaskGroup != nil {
		return *x.TaskGroup
	}
	return ""
}

type TaskListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Data          []*TaskInfo            `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListResp) Reset() {
	*x = TaskListResp{}
	mi := &file_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListResp) ProtoMessage() {}

func (x *TaskListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListResp.ProtoReflect.Descriptor instead.
func (*TaskListResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{9}
}

func (x *TaskListResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskListResp) GetData() []*TaskInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskLogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id"`
	CreatedAt     *int64                 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at"`
	UpdatedAt     *int64                 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at"`
	StartedAt     *int64                 `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at"`
	FinishedAt    *int64                 `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at"`
	Result        *uint32                `protobuf:"varint,6,opt,name=result,proto3,oneof" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogInfo) Reset() {
	*x = TaskLogInfo{}
	mi := &file_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogInfo) ProtoMessage() {}

func (x *TaskLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogInfo.ProtoReflect.Descriptor instead.
func (*TaskLogInfo) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{10}
}

func (x *TaskLogInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TaskLogInfo) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *TaskLogInfo) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *TaskLogInfo) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *TaskLogInfo) GetFinishedAt() int64 {
	if x != nil && x.FinishedAt != nil {
		return *x.FinishedAt
	}
	return 0
}

func (x *TaskLogInfo) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type TaskLogListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TaskId        *uint64                `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id"`
	Result        *uint32                `protobuf:"varint,4,opt,name=result,proto3,oneof" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogListReq) Reset() {
	*x = TaskLogListReq{}
	mi := &file_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogListReq) ProtoMessage() {}

func (x *TaskLogListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogListReq.ProtoReflect.Descriptor instead.
func (*TaskLogListReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{11}
}

func (x *TaskLogListReq) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TaskLogListReq) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *TaskLogListReq) GetTaskId() uint64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *TaskLogListReq) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type TaskLogListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Data          []*TaskLogInfo         `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogListResp) Reset() {
	*x = TaskLogListResp{}
	mi := &file_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogListResp) ProtoMessage() {}

func (x *TaskLogListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogListResp.ProtoReflect.Descriptor instead.
func (*TaskLogListResp) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{12}
}

func (x *TaskLogListResp) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskLogListResp) GetData() []*TaskLogInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UUIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDReq) Reset() {
	*x = UUIDReq{}
	mi := &file_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDReq) ProtoMessage() {}

func (x *UUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDReq.ProtoReflect.Descriptor instead.
func (*UUIDReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{13}
}

func (x *UUIDReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UUIDsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDsReq) Reset() {
	*x = UUIDsReq{}
	mi := &file_job_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDsReq) ProtoMessage() {}

func (x *UUIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDsReq.ProtoReflect.Descriptor instead.
func (*UUIDsReq) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{14}
}

func (x *UUIDsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\x12\x03job\".\n" +
	"\n" +
	"BaseIDResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1c\n" +
	"\bBaseResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"0\n" +
	"\fBaseUUIDResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x05IDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x1a\n" +
	"\x06IDsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\">\n" +
	"\vPageInfoReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\"\xa1\x03\n" +
	"\bTaskInfo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03H\x01R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03H\x02R\tupdatedAt\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\rH\x03R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x04R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"task_group\x18\x06 \x01(\tH\x05R\ttaskGroup\x88\x01\x01\x12,\n" +
	"\x0fcron_expression\x18\a \x01(\tH\x06R\x0ecronExpression\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\b \x01(\tH\aR\apattern\x88\x01\x01\x12\x1d\n" +
	"\apayload\x18\t \x01(\tH\bR\apayload\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\t\n" +
	"\a_statusB\a\n" +
	"\x05_nameB\r\n" +
	"\v_task_groupB\x12\n" +
	"\x10_cron_expressionB\n" +
	"\n" +
	"\b_patternB\n" +
	"\n" +
	"\b_payload\"\x93\x01\n" +
	"\vTaskListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"task_group\x18\x04 \x01(\tH\x01R\ttaskGroup\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_task_group\"G\n" +
	"\fTaskListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12!\n" +
	"\x04data\x18\x02 \x03(\v2\r.job.TaskInfoR\x04data\"\xa0\x02\n" +
	"\vTaskLogInfo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03H\x01R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03H\x02R\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03H\x03R\tstartedAt\x88\x01\x01\x12$\n" +
	"\vfinished_at\x18\x05 \x01(\x03H\x04R\n" +
	"finishedAt\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x06 \x01(\rH\x05R\x06result\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_started_atB\x0e\n" +
	"\f_finished_atB\t\n" +
	"\a_result\"\x93\x01\n" +
	"\x0eTaskLogListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x1c\n" +
	"\atask_id\x18\x03 \x01(\x04H\x00R\x06taskId\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x04 \x01(\rH\x01R\x06result\x88\x01\x01B\n" +
	"\n" +
	"\b_task_idB\t\n" +
	"\a_result\"M\n" +
	"\x0fTaskLogListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.job.TaskLogInfoR\x04data\"\x19\n" +
	"\aUUIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\bUUIDsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids2\x92\x04\n" +
	"\x03Job\x12)\n" +
	"\finitDatabase\x12\n" +
	".job.Empty\x1a\r.job.BaseResp\x12,\n" +
	"\n" +
	"createTask\x12\r.job.TaskInfo\x1a\x0f.job.BaseIDResp\x12*\n" +
	"\n" +
	"updateTask\x12\r.job.TaskInfo\x1a\r.job.BaseResp\x122\n" +
	"\vgetTaskList\x12\x10.job.TaskListReq\x1a\x11.job.TaskListResp\x12(\n" +
	"\vgetTaskById\x12\n" +
	".job.IDReq\x1a\r.job.TaskInfo\x12(\n" +
	"\n" +
	"deleteTask\x12\v.job.IDsReq\x1a\r.job.BaseResp\x122\n" +
	"\rcreateTaskLog\x12\x10.job.TaskLogInfo\x1a\x0f.job.BaseIDResp\x120\n" +
	"\rupdateTaskLog\x12\x10.job.TaskLogInfo\x1a\r.job.BaseResp\x12;\n" +
	"\x0egetTaskLogList\x12\x13.job.TaskLogListReq\x1a\x14.job.TaskLogListResp\x12.\n" +
	"\x0egetTaskLogById\x12\n" +
	".job.IDReq\x1a\x10.job.TaskLogInfo\x12+\n" +
	"\rdeleteTaskLog\x12\v.job.IDsReq\x1a\r.job.BaseRespB\aZ\x05./jobb\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_job_proto_goTypes = []any{
	(*BaseIDResp)(nil),      // 0: job.BaseIDResp
	(*BaseResp)(nil),        // 1: job.BaseResp
	(*BaseUUIDResp)(nil),    // 2: job.BaseUUIDResp
	(*Empty)(nil),           // 3: job.Empty
	(*IDReq)(nil),           // 4: job.IDReq
	(*IDsReq)(nil),          // 5: job.IDsReq
	(*PageInfoReq)(nil),     // 6: job.PageInfoReq
	(*TaskInfo)(nil),        // 7: job.TaskInfo
	(*TaskListReq)(nil),     // 8: job.TaskListReq
	(*TaskListResp)(nil),    // 9: job.TaskListResp
	(*TaskLogInfo)(nil),     // 10: job.TaskLogInfo
	(*TaskLogListReq)(nil),  // 11: job.TaskLogListReq
	(*TaskLogListResp)(nil), // 12: job.TaskLogListResp
	(*UUIDReq)(nil),         // 13: job.UUIDReq
	(*UUIDsReq)(nil),        // 14: job.UUIDsReq
}
var file_job_proto_depIdxs = []int32{
	7,  // 0: job.TaskListResp.data:type_name -> job.TaskInfo
	10, // 1: job.TaskLogListResp.data:type_name -> job.TaskLogInfo
	3,  // 2: job.Job.initDatabase:input_type -> job.Empty
	7,  // 3: job.Job.createTask:input_type -> job.TaskInfo
	7,  // 4: job.Job.updateTask:input_type -> job.TaskInfo
	8,  // 5: job.Job.getTaskList:input_type -> job.TaskListReq
	4,  // 6: job.Job.getTaskById:input_type -> job.IDReq
	5,  // 7: job.Job.deleteTask:input_type -> job.IDsReq
	10, // 8: job.Job.createTaskLog:input_type -> job.TaskLogInfo
	10, // 9: job.Job.updateTaskLog:input_type -> job.TaskLogInfo
	11, // 10: job.Job.getTaskLogList:input_type -> job.TaskLogListReq
	4,  // 11: job.Job.getTaskLogById:input_type -> job.IDReq
	5,  // 12: job.Job.deleteTaskLog:input_type -> job.IDsReq
	1,  // 13: job.Job.initDatabase:output_type -> job.BaseResp
	0,  // 14: job.Job.createTask:output_type -> job.BaseIDResp
	1,  // 15: job.Job.updateTask:output_type -> job.BaseResp
	9,  // 16: job.Job.getTaskList:output_type -> job.TaskListResp
	7,  // 17: job.Job.getTaskById:output_type -> job.TaskInfo
	1,  // 18: job.Job.deleteTask:output_type -> job.BaseResp
	0,  // 19: job.Job.createTaskLog:output_type -> job.BaseIDResp
	1,  // 20: job.Job.updateTaskLog:output_type -> job.BaseResp
	12, // 21: job.Job.getTaskLogList:output_type -> job.TaskLogListResp
	10, // 22: job.Job.getTaskLogById:output_type -> job.TaskLogInfo
	1,  // 23: job.Job.deleteTaskLog:output_type -> job.BaseResp
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	file_job_proto_msgTypes[7].OneofWrappers = []any{}
	file_job_proto_msgTypes[8].OneofWrappers = []any{}
	file_job_proto_msgTypes[10].OneofWrappers = []any{}
	file_job_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
