// Code generated by goctl. DO NOT EDIT.
// Source: job.proto

package server

import (
	"context"

	"github.com/suyuan32/simple-admin-job/internal/logic/base"
	"github.com/suyuan32/simple-admin-job/internal/svc"
	"github.com/suyuan32/simple-admin-job/job"
)

type JobServer struct {
	svcCtx *svc.ServiceContext
	job.UnimplementedJobServer
}

func NewJobServer(svcCtx *svc.ServiceContext) *JobServer {
	return &JobServer{
		svcCtx: svcCtx,
	}
}

func (s *JobServer) InitDatabase(ctx context.Context, in *job.Empty) (*job.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
