// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysTasksColumns holds the columns for the "sys_tasks" table.
	SysTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "Task Name | 任务名称"},
		{Name: "task_group", Type: field.TypeString, Comment: "Task Group | 任务分组"},
		{Name: "cron_expression", Type: field.TypeString, Comment: "Cron expression | 定时任务表达式"},
		{Name: "pattern", Type: field.TypeString, Comment: "Cron Pattern | 任务的模式 （用于区分和确定要执行的任务）"},
		{Name: "payload", Type: field.TypeString, Comment: "The data used in cron (JSON string) | 任务需要的数据(JSON 字符串)"},
	}
	// SysTasksTable holds the schema information for the "sys_tasks" table.
	SysTasksTable = &schema.Table{
		Name:       "sys_tasks",
		Comment:    "Task Configuration Table | 任务配置表",
		Columns:    SysTasksColumns,
		PrimaryKey: []*schema.Column{SysTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "task_pattern",
				Unique:  true,
				Columns: []*schema.Column{SysTasksColumns[7]},
			},
		},
	}
	// SysTaskLogsColumns holds the columns for the "sys_task_logs" table.
	SysTaskLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "started_at", Type: field.TypeTime, Comment: "Task Started Time | 任务启动时间"},
		{Name: "finished_at", Type: field.TypeTime, Comment: "Task Finished Time | 任务完成时间"},
		{Name: "result", Type: field.TypeUint8, Comment: "The Task Process Result | 任务执行结果"},
		{Name: "task_task_logs", Type: field.TypeUint64, Nullable: true},
	}
	// SysTaskLogsTable holds the schema information for the "sys_task_logs" table.
	SysTaskLogsTable = &schema.Table{
		Name:       "sys_task_logs",
		Comment:    "Task Log Table | 任务日志表",
		Columns:    SysTaskLogsColumns,
		PrimaryKey: []*schema.Column{SysTaskLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_task_logs_sys_tasks_task_logs",
				Columns:    []*schema.Column{SysTaskLogsColumns[4]},
				RefColumns: []*schema.Column{SysTasksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysTasksTable,
		SysTaskLogsTable,
	}
)

func init() {
	SysTasksTable.Annotation = &entsql.Annotation{
		Table: "sys_tasks",
	}
	SysTaskLogsTable.ForeignKeys[0].RefTable = SysTasksTable
	SysTaskLogsTable.Annotation = &entsql.Annotation{
		Table: "sys_task_logs",
	}
}
