// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdate) SetNotEmptyStatus(value uint8) *TaskUpdate {
	if value != 0 {
		return t.SetStatus(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdateOne) SetNotEmptyStatus(value uint8) *TaskUpdateOne {
	if value != 0 {
		return t.SetStatus(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdate) SetNotEmptyName(value string) *TaskUpdate {
	if value != "" {
		return t.SetName(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdateOne) SetNotEmptyName(value string) *TaskUpdateOne {
	if value != "" {
		return t.SetName(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdate) SetNotEmptyTaskGroup(value string) *TaskUpdate {
	if value != "" {
		return t.SetTaskGroup(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdateOne) SetNotEmptyTaskGroup(value string) *TaskUpdateOne {
	if value != "" {
		return t.SetTaskGroup(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdate) SetNotEmptyCronExpression(value string) *TaskUpdate {
	if value != "" {
		return t.SetCronExpression(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdateOne) SetNotEmptyCronExpression(value string) *TaskUpdateOne {
	if value != "" {
		return t.SetCronExpression(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdate) SetNotEmptyPattern(value string) *TaskUpdate {
	if value != "" {
		return t.SetPattern(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdateOne) SetNotEmptyPattern(value string) *TaskUpdateOne {
	if value != "" {
		return t.SetPattern(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdate) SetNotEmptyPayload(value string) *TaskUpdate {
	if value != "" {
		return t.SetPayload(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdateOne) SetNotEmptyPayload(value string) *TaskUpdateOne {
	if value != "" {
		return t.SetPayload(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdate) SetNotEmptyEntryID(value int) *TaskUpdate {
	if value != 0 {
		return t.SetEntryID(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TaskUpdateOne) SetNotEmptyEntryID(value int) *TaskUpdateOne {
	if value != 0 {
		return t.SetEntryID(value)
	}
	return t
}
