// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (t *TaskUpdate) SetNotNilUpdatedAt(value *time.Time) *TaskUpdate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdateOne) SetNotNilUpdatedAt(value *time.Time) *TaskUpdateOne {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskCreate) SetNotNilUpdatedAt(value *time.Time) *TaskCreate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdate) SetNotNilStatus(value *uint8) *TaskUpdate {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdateOne) SetNotNilStatus(value *uint8) *TaskUpdateOne {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskCreate) SetNotNilStatus(value *uint8) *TaskCreate {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdate) SetNotNilName(value *string) *TaskUpdate {
	if value != nil {
		return t.SetName(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdateOne) SetNotNilName(value *string) *TaskUpdateOne {
	if value != nil {
		return t.SetName(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskCreate) SetNotNilName(value *string) *TaskCreate {
	if value != nil {
		return t.SetName(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdate) SetNotNilTaskGroup(value *string) *TaskUpdate {
	if value != nil {
		return t.SetTaskGroup(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdateOne) SetNotNilTaskGroup(value *string) *TaskUpdateOne {
	if value != nil {
		return t.SetTaskGroup(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskCreate) SetNotNilTaskGroup(value *string) *TaskCreate {
	if value != nil {
		return t.SetTaskGroup(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdate) SetNotNilCronExpression(value *string) *TaskUpdate {
	if value != nil {
		return t.SetCronExpression(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdateOne) SetNotNilCronExpression(value *string) *TaskUpdateOne {
	if value != nil {
		return t.SetCronExpression(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskCreate) SetNotNilCronExpression(value *string) *TaskCreate {
	if value != nil {
		return t.SetCronExpression(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdate) SetNotNilPattern(value *string) *TaskUpdate {
	if value != nil {
		return t.SetPattern(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdateOne) SetNotNilPattern(value *string) *TaskUpdateOne {
	if value != nil {
		return t.SetPattern(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskCreate) SetNotNilPattern(value *string) *TaskCreate {
	if value != nil {
		return t.SetPattern(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdate) SetNotNilPayload(value *string) *TaskUpdate {
	if value != nil {
		return t.SetPayload(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskUpdateOne) SetNotNilPayload(value *string) *TaskUpdateOne {
	if value != nil {
		return t.SetPayload(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TaskCreate) SetNotNilPayload(value *string) *TaskCreate {
	if value != nil {
		return t.SetPayload(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (tl *TaskLogUpdate) SetNotNilFinishedAt(value *time.Time) *TaskLogUpdate {
	if value != nil {
		return tl.SetFinishedAt(*value)
	}
	return tl
}

// set field if value's pointer is not nil.
func (tl *TaskLogUpdateOne) SetNotNilFinishedAt(value *time.Time) *TaskLogUpdateOne {
	if value != nil {
		return tl.SetFinishedAt(*value)
	}
	return tl
}

// set field if value's pointer is not nil.
func (tl *TaskLogCreate) SetNotNilFinishedAt(value *time.Time) *TaskLogCreate {
	if value != nil {
		return tl.SetFinishedAt(*value)
	}
	return tl
}

// set field if value's pointer is not nil.
func (tl *TaskLogUpdate) SetNotNilResult(value *uint8) *TaskLogUpdate {
	if value != nil {
		return tl.SetResult(*value)
	}
	return tl
}

// set field if value's pointer is not nil.
func (tl *TaskLogUpdateOne) SetNotNilResult(value *uint8) *TaskLogUpdateOne {
	if value != nil {
		return tl.SetResult(*value)
	}
	return tl
}

// set field if value's pointer is not nil.
func (tl *TaskLogCreate) SetNotNilResult(value *uint8) *TaskLogCreate {
	if value != nil {
		return tl.SetResult(*value)
	}
	return tl
}
