// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskLog is the predicate function for tasklog builders.
type TaskLog func(*sql.Selector)
